---
- name: add php apt key
  apt_key:
    url: https://packages.sury.org/php/apt.gpg

- name: add php apt source
  apt_repository:
    repo: "deb https://packages.sury.org/php/ {{ ansible_distribution_release }} main"

- name: install php packages
  apt:
    pkg:
      - php7.4
      - php7.4-cli
      - php7.4-fpm
      - php7.4-curl
      - php7.4-mbstring
      - php7.4-opcache
      - php7.4-pgsql
      - php7.4-xml
      - php7.4-zip
    state: present
    update-cache: yes


# if nginx is installed, make sure it can talk to php-fpm
- name: Determine available groups
  getent:
    database: passwd

- name: Add additional groups to user
  user: name="nginx" groups="www-data" append=yes
  when: '"nginx" in getent_passwd'
