---
- hosts: roger.lghs.space
  become: yes
  roles:
    - members.lghs.be
    - role: static-site
      vars:
        vhost: lghs.be

- hosts: sparkle.lghs.space
  become: yes
  roles:
    - ldap
    - accounting.lghs.be

- hosts: escandalo.lghs.space
  become: yes
  roles:
    - chat.lghs.be
