---
#
# Global stuff
#
- hosts: all
  become: yes
  roles:
    - common

- hosts: web
  become: yes
  roles:
    - web-server

- hosts: database
  become: yes
  roles:
    - database-server


#
# Specific applications
#
- hosts: roger.lghs.space
  become: yes
  roles:
    - members.lghs.be
    - role: static-site
      vars:
        vhost: lghs.be

- hosts: sparkle.lghs.space
  become: yes
  roles:
    - accounting.lghs.be

- hosts: escandalo.lghs.space
  become: yes
  roles:
    - chat.lghs.be
